[package]
name = "zero"
version.workspace = true
edition.workspace = true

[dependencies]
embassy-sync.workspace = true
log.workspace = true
phf.workspace = true

buffer-tool.workspace = true
physical-values.workspace = true
volatile-value.workspace = true

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
embassy-sync = {workspace = true, features = ["std"]}
embassy-time = {workspace = true, features = ["std"]}
